# -*- coding: utf-8 -*-
"""
THƯ VIỆN HỆ NHÔM SAO VÀNG - Master Data Core
Bộ dữ liệu kỹ thuật gốc tổng hợp từ catalogue các hãng nhôm
Phiên bản: 2.0 - Cập nhật 2026
"""

# =========================================================
# PHẦN 1: DỮ LIỆU KỸ THUẬT TOÀN BỘ HỆ NHÔM (150+ hệ)
# =========================================================
# Cấu trúc mỗi hệ:
# (ID, Nhóm, Mã_Hệ, Hãng, Quốc_Gia, Tiêu_Chuẩn, Loại_Cửa,
#  Kiểu_Mở, Loại_Profile, Công_Năng, Ứng_Dụng, 
#  Độ_Dày_Nhôm_mm, Kính_Tương_Thích_mm, Kính_Tối_Đa_mm,
#  Kích_Thước_Tối_Đa_W_x_H, Tải_Trọng_Cánh_kg,
#  Chuẩn_Phụ_Kiện, Gioăng_Keo, Bề_Mặt_Đặc_Tính,
#  Ưu_Điểm, Nhược_Điểm,
#  CAD, Shopdrawing, Catalogue, HD_Lắp_Đặt,
#  Tình_Trạng, Hoàn_Thiện_Pct, Link_Web, Link_Catalogue)

MASTER_DATA = [

    # ============================================================
    # VIRALWINDOW (VR) - VIETNAM
    # ============================================================
    ("VR-001", "Anodized - Phổ thông", "VRA55", "Viralwindow", "Việt Nam", "TCVN 5826",
     "Cửa đi + Cửa sổ", "Mở quay (Casement)", "Khung + Cánh",
     "Nội thất + Ngoại thất", "Nhà phố, chung cư phổ thông",
     1.4, "Kính đơn 5-10mm", "10mm",
     "1200 × 2400 mm", 80,
     "Rãnh 22mm truyền thống", "Gioăng EPDM đơn khoang / Keo bọt PU + silicon",
     "Sơn tĩnh điện trắng, vàng champagne, đen bóng, nâu gỗ",
     "Giá cạnh tranh, phổ biến thị trường miền Nam, đa dạng màu sắc",
     "Độ cứng thấp hơn hệ 65, giới hạn tải trọng cánh, không phù hợp cửa rộng lớn",
     "✓", "✓", "✓", "✓", "Hoàn thành", 90, "https://viralwindow.com", ""),

    ("VR-002", "Anodized - Trung cấp", "VRA65", "Viralwindow", "Việt Nam", "TCVN 5826",
     "Cửa đi + Cửa sổ", "Mở quay (Casement)", "Khung + Cánh",
     "Ngoại thất", "Biệt thự, nhà phố cao cấp",
     1.6, "Kính đơn 5-12mm / Kính hộp 20-28mm", "12mm",
     "1400 × 2600 mm", 120,
     "Rãnh C (Euro Groove)", "Gioăng EPDM đa khoang / Silicon Dow Corning",
     "Anodized bạc, sơn tĩnh điện bột AkzoNobel",
     "Cứng vững hơn VRA55, phù hợp cửa sổ lớn và cửa đi đơn 2 cánh, profile đẹp mắt",
     "Giá cao hơn VRA55, cần thợ có kinh nghiệm khi lắp cửa lớn",
     "✓", "✓", "✓", "✓", "Hoàn thành", 90, "https://viralwindow.com", ""),

    ("VR-003", "Trượt lùa - Phổ thông", "VRS65", "Viralwindow", "Việt Nam", "TCVN 5826",
     "Cửa đi + Cửa sổ", "Trượt lùa (Sliding)", "Khung + Cánh + Ray",
     "Ngoại thất + Ban công", "Nhà phố, căn hộ, ban công",
     1.6, "Kính đơn 8-12mm / Kính hộp 20-28mm", "12mm",
     "3000 × 2400 mm", 150,
     "Rãnh C (Euro Groove)", "Gioăng EPDM kín nước / Silicon trung tính",
     "Sơn tĩnh điện đa màu, anodized",
     "Phù hợp ban công rộng, có thể ghép nhiều cánh lùa liên tiếp, giá cạnh tranh",
     "Cần bảo dưỡng bánh xe định kỳ, kín khít không bằng hệ Lift Slide",
     "✓", "✓", "✓", "✓", "Hoàn thành", 85, "https://viralwindow.com", ""),

    ("VR-004", "Trượt quay - Cao cấp", "VRSD", "Viralwindow", "Việt Nam", "TCVN 5826",
     "Cửa đi", "Trượt quay (Sliding + Pivot)", "Khung + Cánh đặc biệt",
     "Ngoại thất", "Biệt thự cao cấp, nhà phố sang trọng",
     1.8, "Kính cường lực 10-12mm", "12mm",
     "1200 × 2800 mm", 120,
     "Phụ kiện Slido / Häfele đặc chủng", "Gioăng EPDM nén phẳng / Silicon Dow Corning",
     "Anodized ED chống muối biển, sơn tĩnh điện mờ",
     "Thẩm mỹ cao, vận hành trơn tru 180°, không ray dưới sàn",
     "Giá cao, yêu cầu lắp đặt chính xác theo template, tải trọng có giới hạn",
     "✓", "✓", "✓", "✓", "Hoàn thành", 80, "https://viralwindow.com", ""),

    ("VR-005", "Thủy lực - Siêu cao cấp", "VRHL", "Viralwindow", "Việt Nam", "TCVN",
     "Cửa đi", "Thủy lực (Hydraulic / Zero Gravity)", "Khung + Cánh siêu nặng",
     "Ngoại thất", "Biệt thự siêu cao cấp, villa resort, penthouse",
     2.0, "Kính hộp 36-50mm / Kính cường lực 15-19mm", "19mm",
     "3500 × 3500 mm", 800,
     "Phụ kiện thủy lực Dorma / DICTATOR / Biloba", "Keo silicon kết cấu SG / EPDM giả thép",
     "Anodized ED vàng 24K, đồng đỏ, sơn RAL theo yêu cầu",
     "Cửa siêu rộng siêu cao, tải trọng cực lớn, tự đóng chậm bằng piston thủy lực, thẩm mỹ đỉnh cao",
     "Giá cực cao (300-900 triệu/bộ), yêu cầu khung bê tông cốt thép gia cố, thợ kỹ thuật cao",
     "✓", "✓", "✓", "✓", "Hoàn thành", 85, "https://viralwindow.com", ""),

    ("VR-006", "Lift & Slide - Cao cấp", "VRLS", "Viralwindow", "Việt Nam", "TCVN",
     "Cửa đi", "Trượt nâng (Lift & Slide)", "Khung + Cánh + Ray đặc biệt",
     "Ngoại thất", "Biệt thự, nhà phố cao cấp, lối ra sân vườn",
     2.0, "Kính hộp 24-48mm / Kính cường lực 12-19mm", "19mm",
     "6000 × 2800 mm", 400,
     "Phụ kiện Roto NT / Siegenia LSS", "Gioăng EPDM đa khoang / Silicon Dow Corning",
     "Anodized, sơn tĩnh điện bột",
     "Kín khít hoàn toàn khi đóng (tay nắm nâng cánh khỏi ngưỡng), mở nhẹ dù cánh cực nặng",
     "Giá cao hơn cửa lùa thông thường, cần ray thẳng tuyệt đối",
     "✓", "✓", "✓", "✓", "Hoàn thành", 80, "https://viralwindow.com", ""),

    ("VR-007", "Mở hất - Phổ thông", "VRAW", "Viralwindow", "Việt Nam", "TCVN",
     "Cửa sổ", "Mở hất (Awning / Top Hung)", "Khung + Cánh",
     "Ngoại thất", "Nhà phố, chung cư, nhà xưởng",
     1.4, "Kính đơn 5-10mm", "10mm",
     "1200 × 800 mm", 30,
     "Rãnh 22mm / Rãnh C", "Gioăng EPDM / Silicon trung tính",
     "Sơn tĩnh điện",
     "Che mưa khi mở, thông gió tốt, giá rẻ",
     "Tải trọng giới hạn, không phù hợp cửa lớn",
     "✓", "✗", "✓", "✓", "Hoàn thành", 75, "https://viralwindow.com", ""),

    ("VR-008", "Xếp trượt - Cao cấp", "VRBF", "Viralwindow", "Việt Nam", "TCVN",
     "Cửa đi", "Xếp trượt (Bi-fold)", "Khung + Cánh + Ray + Bản lề xếp",
     "Ngoại thất", "Biệt thự, nhà hàng, quán cà phê, lối ra sân",
     1.8, "Kính cường lực 8-12mm", "12mm",
     "5000 × 2600 mm", 40,
     "Phụ kiện Roto Fold / Hopo Bi-fold", "Gioăng EPDM / Silicon",
     "Sơn tĩnh điện, anodized",
     "Mở toàn bộ không gian, xếp gọn một bên, phù hợp không gian mở",
     "Kín khít kém hơn hệ lùa, cần bảo dưỡng định kỳ, tải trọng mỗi cánh hạn chế",
     "✓", "✗", "✓", "✓", "Đang nghiên cứu", 60, "https://viralwindow.com", ""),

    # ============================================================
    # CIVRO - VIETNAM (Sản xuất tại Việt Nam, thiết kế Châu Âu)
    # ============================================================
    ("CV-001", "Anodized - Trung cấp", "CWS55", "Civro", "Việt Nam", "EN 12207 / EN 12210",
     "Cửa sổ + Cửa đi", "Mở quay (Casement)", "Khung + Cánh",
     "Ngoại thất", "Nhà phố, chung cư trung cấp",
     1.5, "Kính đơn 5-10mm", "10mm",
     "1200 × 2200 mm", 80,
     "Rãnh C (Euro Groove)", "Gioăng EPDM 3 vòng kín / Silicon trung tính Dow",
     "Sơn tĩnh điện bột, anodized bạc",
     "Hệ châu Âu giá Việt Nam, phù hợp dự án nhà ở phổ thông",
     "Ít tùy chọn màu sắc hơn hệ 65",
     "✓", "✓", "✓", "✓", "Hoàn thành", 85, "https://civrowindow.com", ""),

    ("CV-002", "Anodized - Cao cấp", "CWS65", "Civro", "Việt Nam", "EN 12207 / EN 12210",
     "Cửa sổ + Cửa đi", "Mở quay (Casement)", "Khung + Cánh + Cánh giả",
     "Ngoại thất", "Biệt thự, nhà phố cao cấp, văn phòng",
     1.8, "Kính đơn 8-12mm / Kính hộp 20-32mm", "14mm",
     "1600 × 2800 mm", 150,
     "Rãnh C (Euro Groove) - tương thích Roto, Siegenia, Maco",
     "Gioăng EPDM đa khoang 3 lớp kín / Silicon Dow Corning 795",
     "Anodized ED, sơn PVDF cao cấp, wood-look décor",
     "Cứng vững, phù hợp cửa sổ lớn và vách cố định, hệ phụ kiện Châu Âu đầy đủ",
     "Giá trung-cao, cần thợ chuyên nghiệp lắp đặt",
     "✓", "✓", "✓", "✓", "Hoàn thành", 90, "https://civrowindow.com", ""),

    ("CV-003", "Anodized - Siêu cao cấp", "CWS75", "Civro", "Việt Nam", "EN 12207 / EN 12210",
     "Cửa sổ + Cửa đi", "Mở quay + Mở hất (Casement + Awning)", "Khung + Cánh",
     "Ngoại thất", "Biệt thự cao cấp, khách sạn, resort 5 sao",
     2.0, "Kính đơn 10-14mm / Kính hộp 24-36mm", "16mm",
     "2000 × 3000 mm", 200,
     "Rãnh C (Euro Groove) cao cấp", "Gioăng EPDM 4 lớp / Silicon Dow Corning 791",
     "Anodized ED, sơn PVDF 2 lớp, wood finish",
     "Profile dày nhất trong dòng Civro, cách âm vượt trội, phù hợp công trình hạng sang",
     "Giá rất cao, thi công phức tạp",
     "✓", "✓", "✓", "✓", "Hoàn thành", 85, "https://civrowindow.com", ""),

    ("CV-004", "Cầu cách nhiệt - Cao cấp", "CAW65IN", "Civro", "Việt Nam", "EN 14351-1",
     "Cửa sổ + Cửa đi", "Mở quay (Casement)", "Khung cầu cách nhiệt PA66",
     "Ngoại thất - Công trình xanh", "Công trình xanh, khách sạn, văn phòng LEED",
     2.0, "Kính hộp Low-E 24-36mm / Kính 3 lớp 44mm", "18mm",
     "1400 × 2800 mm", 150,
     "Rãnh C (Euro Groove) cách nhiệt", "Gioăng EPDM cách nhiệt 3 lớp / Silicon Dow Corning 795",
     "Anodized tách 2 màu (trong/ngoài), sơn PVDF, wood-look",
     "Uf < 1.8 W/(m²K), chống đọng sương, cách âm > 38dB, phù hợp khí hậu nhiệt đới",
     "Giá cao hơn 40-60% so với hệ thường, cần thiết kế kỹ lưỡng về nhiệt",
     "✓", "✓", "✓", "✓", "Hoàn thành", 90, "https://civrowindow.com", ""),

    ("CV-005", "Cầu cách nhiệt - Siêu cao cấp", "CAW75IN", "Civro", "Việt Nam", "EN 14351-1",
     "Cửa sổ + Cửa đi", "Mở quay + Mở hất (Casement + Tilt-Turn)", "Khung cầu cách nhiệt PA66",
     "Ngoại thất - Passive House", "Khách sạn 5 sao, Passive House, công trình xanh 5 sao",
     2.0, "Kính 3 lớp 44-52mm", "20mm",
     "1800 × 3000 mm", 200,
     "Rãnh C Châu Âu đặc biệt", "Gioăng EPDM 4 lớp cách nhiệt / Silicon Dow Corning",
     "Anodized tách màu trong ngoài, sơn RAL PVDF",
     "Uf < 1.0 W/(m²K), đạt tiêu chuẩn Passive House, cách âm > 45dB",
     "Giá rất cao, thị trường hạn chế",
     "✓", "✓", "✓", "✓", "Đang nghiên cứu", 70, "https://civrowindow.com", ""),

    ("CV-006", "Trượt lùa - Cao cấp", "CSD80", "Civro", "Việt Nam", "EN 13830",
     "Cửa đi", "Trượt lùa (Sliding)", "Khung + Cánh + Ray thép inox",
     "Ngoại thất", "Biệt thự, lối ra sân vườn hồ bơi",
     2.0, "Kính cường lực 10-15mm / Kính hộp 24-36mm", "15mm",
     "4000 × 2600 mm", 200,
     "Ray inox SUS316L chống muối biển", "Gioăng EPDM kép / Silicon cấu trúc",
     "Anodized ED biển, sơn PVDF chống ăn mòn",
     "Phù hợp biệt thự biển, chịu muối, trượt êm trên ray inox",
     "Nặng, cần khoảng tường để cánh trượt vào, thi công phức tạp",
     "✓", "✓", "✓", "✓", "Hoàn thành", 80, "https://civrowindow.com", ""),

    ("CV-007", "Lift & Slide - Cao cấp", "CLSS80", "Civro", "Việt Nam", "EN 13830",
     "Cửa đi", "Trượt nâng (Lift & Slide)", "Khung + Cánh + Phụ kiện LSS",
     "Ngoại thất", "Biệt thự siêu cao cấp, biệt thự biển, penthouse",
     2.0, "Kính hộp 28-52mm / Kính 3 lớp", "19mm",
     "7000 × 3000 mm", 500,
     "Phụ kiện Siegenia Patio Life / Roto Patio Fold", "Gioăng EPDM cầu cách nhiệt / Silicon Dow",
     "Anodized ED, sơn PVDF 2 thành phần",
     "Mở nhẹ dù 500kg, kín khít hoàn toàn, cách âm và cách nhiệt tốt nhất trong dòng lùa",
     "Giá cao nhất dòng lùa, thi công khó, yêu cầu ray thẳng tuyệt đối",
     "✓", "✓", "✓", "✓", "Hoàn thành", 85, "https://civrowindow.com", ""),

    ("CV-008", "Vách mặt dựng - Stick", "CCW50", "Civro", "Việt Nam", "EN 13830",
     "Vách mặt dựng", "Cố định (Fixed / Stick System)", "Đố đứng + Đố ngang + Nẹp kính",
     "Ngoại thất - Mặt dựng", "Tòa nhà văn phòng, trung tâm thương mại, khách sạn",
     2.0, "Kính hộp 20-36mm / Kính 3 lớp 44mm", "36mm",
     "Không giới hạn (thiết kế theo dự án)", 500,
     "Hệ Stick lắp ghép tại công trường", "Keo silicon kết cấu SG2000 / Keo cấu trúc Sika",
     "Anodized, sơn PVDF, mill finish",
     "Linh hoạt thiết kế, thi công từng thanh tại công trường, dễ sửa chữa",
     "Thi công chậm hơn unitized, yêu cầu kiểm soát chất lượng cao",
     "✓", "✓", "✓", "✓", "Đang nghiên cứu", 70, "https://civrowindow.com", ""),

    # ============================================================
    # MAXPRO JP - VIETNAM (Nhật thiết kế, sản xuất VN)
    # ============================================================
    ("MP-001", "Anodized - Phổ thông", "MP55", "Maxpro JP", "Việt Nam", "TCVN / JIS A 4702",
     "Cửa đi + Cửa sổ", "Mở quay (Casement)", "Khung + Cánh",
     "Nội thất + Ngoại thất", "Nhà phố, căn hộ, nhà xưởng",
     1.4, "Kính đơn 5-10mm", "10mm",
     "1200 × 2200 mm", 80,
     "Rãnh C / Rãnh 22", "Gioăng EPDM 2 khoang / Silicon trung tính",
     "Anodized bạc, sơn tĩnh điện đa màu",
     "Giá phải chăng, tỷ lệ bản rộng mỏng theo thiết kế Nhật, phù hợp dự án đại trà",
     "Độ cứng thấp hơn hệ 65, không phù hợp cửa đi lớn đơn 2 cánh",
     "✓", "✓", "✓", "✓", "Hoàn thành", 85, "https://maxprojp.com.vn", ""),

    ("MP-002", "Anodized - Trung cao cấp", "MP65", "Maxpro JP", "Việt Nam", "TCVN / JIS A 4702",
     "Cửa đi + Cửa sổ", "Mở quay + Mở hất", "Khung + Cánh + Cánh tilt-turn",
     "Ngoại thất", "Biệt thự, nhà phố cao cấp, văn phòng hạng B",
     1.6, "Kính đơn 5-12mm / Kính hộp 20-28mm", "12mm",
     "1600 × 2800 mm", 150,
     "Rãnh C (Euro Groove)", "Gioăng EPDM đa khoang / Keo silicon Sika 11FC",
     "Anodized bạc tự nhiên, sơn tĩnh điện bột, màu theo mã RAL",
     "Hệ phụ kiện Nhật tích hợp sẵn, độ bền cao, profile thanh lịch",
     "Phân phối hạn chế ở miền Bắc",
     "✓", "✓", "✓", "✓", "Hoàn thành", 85, "https://maxprojp.com.vn", ""),

    ("MP-003", "Cầu cách nhiệt - Trung cao cấp", "MPTB65", "Maxpro JP", "Việt Nam", "EN 14351-1",
     "Cửa đi + Cửa sổ", "Mở quay + Mở hất (Casement + Awning)", "Khung cầu cách nhiệt nylon PA66",
     "Ngoại thất - Công trình xanh", "Biệt thự cao cấp, khách sạn, chung cư hạng sang",
     1.8, "Kính hộp Low-E 24-36mm", "16mm",
     "1400 × 2800 mm", 150,
     "Rãnh C cách nhiệt", "Gioăng EPDM cách nhiệt 3 lớp / Silicon Dow Corning",
     "Anodized 2 màu, sơn PVDF, wood-look décor",
     "Uf < 2.0 W/(m²K), hệ Nhật cải tiến cho khí hậu nhiệt đới, phụ kiện nguyên bộ",
     "Giá tương đương Civro thermal nhưng ít hơn Schüco",
     "✓", "✓", "✓", "✓", "Hoàn thành", 80, "https://maxprojp.com.vn", ""),

    ("MP-004", "Trượt lùa - Trung cao cấp", "MPSL80", "Maxpro JP", "Việt Nam", "TCVN",
     "Cửa đi", "Trượt lùa 2-4 cánh (Sliding)", "Khung + Cánh + Ray thép",
     "Ngoại thất", "Biệt thự, ban công chung cư cao cấp",
     1.8, "Kính cường lực 10-15mm / Kính hộp 20-28mm", "15mm",
     "5000 × 2400 mm", 200,
     "Rãnh C / Ray inox SUS304", "Gioăng EPDM / Silicon Dow Corning",
     "Anodized bạc, sơn tĩnh điện, anodized màu champagne",
     "Hệ lùa 4 cánh phổ biến cho biệt thự, vận hành êm",
     "Không phải Lift Slide nên kín không hoàn toàn",
     "✓", "✓", "✓", "✓", "Hoàn thành", 80, "https://maxprojp.com.vn", ""),

    ("MP-005", "Curtain Wall - Stick", "MPCW50", "Maxpro JP", "Việt Nam", "EN 13830",
     "Vách mặt dựng", "Cố định (Fixed - Stick)", "Đố đứng + Đố ngang Maxpro T/I-section",
     "Ngoại thất - Mặt dựng công trình", "Tòa nhà văn phòng, trung tâm thương mại",
     2.0, "Kính hộp 20-32mm / Kính an toàn", "32mm",
     "Không giới hạn (theo thiết kế)", 600,
     "Hệ Stick ghép tại chỗ", "Silicon kết cấu Dow Corning 983 / Sika SikaSil SG-500",
     "Anodized, sơn bột, mill finish",
     "Thiết kế module linh hoạt, chi phí thấp hơn unitized",
     "Thi công chậm, phụ thuộc kiểm soát chất lượng thực địa",
     "✓", "✓", "✓", "✓", "Đang nghiên cứu", 65, "https://maxprojp.com.vn", ""),

    # ============================================================
    # SOCO WINDOW - VIETNAM
    # ============================================================
    ("SC-001", "Lift & Slide - Siêu cao cấp", "Soco LS100", "Soco", "Việt Nam", "EN 13830",
     "Cửa đi", "Trượt nâng (Lift & Slide)", "Khung + Cánh nặng + Ray đặc biệt",
     "Ngoại thất - Siêu biệt thự", "Biệt thự siêu sang, penthouse, biệt thự biển",
     2.5, "Kính hộp 32-60mm / Kính 3 lớp cách nhiệt", "22mm",
     "8000 × 3200 mm", 700,
     "Phụ kiện Roto Patio Life / Siegenia Titan LSS", "Gioăng EPDM cầu cách nhiệt 4 lớp",
     "Anodized ED biển chống ăn mòn, sơn RAL PVDF 2 lớp, gỗ tự nhiên ốp mặt trong",
     "Cửa Lift Slide rộng nhất Việt Nam (đến 8m), nâng êm 700kg, kín khít đạt EN 12208 Cls 9A",
     "Giá dự án từ 500 triệu đến 2 tỷ/bộ tùy kích thước",
     "✓", "✓", "✓", "✓", "Hoàn thành", 90, "https://nhomsocowindow.com", ""),

    ("SC-002", "Curtain Wall - Unitized", "Soco UCW", "Soco", "Việt Nam", "EN 13830 / AAMA 501",
     "Vách mặt dựng", "Panel đúc sẵn (Unitized)", "Panel frame đúc sẵn tại xưởng",
     "Ngoại thất - Tòa nhà cao tầng", "Tòa nhà văn phòng hạng A, khách sạn 5 sao, tòa nhà cao tầng",
     2.5, "Kính hộp Low-E 28-42mm / Kính 3 lớp 48mm", "42mm",
     "Không giới hạn (theo module thiết kế)", 800,
     "Hệ Unitized panel lắp ghép crane", "Silicon kết cấu Dow Corning 983 + Sealant TS",
     "Anodized, PVDF 70% 2 lớp, sơn đặc chủng theo dự án",
     "Thi công nhanh, chất lượng đồng đều, đạt tiêu chuẩn tòa nhà cao tầng AAMA",
     "Chi phí thiết kế mold cao, không linh hoạt sửa đổi",
     "✓", "✓", "✓", "✓", "Đang nghiên cứu", 70, "https://nhomsocowindow.com", ""),

    ("SC-003", "Trượt lùa - Cao cấp", "Soco SD90", "Soco", "Việt Nam", "TCVN",
     "Cửa đi", "Trượt lùa (Sliding)", "Khung + Cánh + Ray inox SUS316",
     "Ngoại thất", "Biệt thự biển, nhà phố cao cấp, resort",
     2.0, "Kính cường lực 10-15mm / Kính hộp 24-36mm", "15mm",
     "5000 × 2800 mm", 250,
     "Ray inox SUS316L chống muối biển", "Gioăng EPDM 3 khoang / Silicon Dow Corning",
     "Anodized ED chống muối biển chuẩn AS 1734-5",
     "Chống ăn mòn muối biển, trượt êm, phù hợp biệt thự duyên hải",
     "Giá cao hơn hệ SD thường do inox SUS316",
     "✓", "✓", "✓", "✓", "Hoàn thành", 80, "https://nhomsocowindow.com", ""),

    # ============================================================
    # PAG - NHÔM CẦU CÁCH NHIỆT - VIETNAM
    # ============================================================
    ("PG-001", "Cầu cách nhiệt - Trung cấp", "PAG60TB", "PAG", "Việt Nam", "EN 14351-1",
     "Cửa sổ + Cửa đi", "Mở quay (Casement)", "Khung cầu cách nhiệt PA66 GF25",
     "Ngoại thất - Công trình xanh", "Nhà phố cao cấp, chung cư xanh, văn phòng",
     1.6, "Kính hộp Low-E 20-28mm", "14mm",
     "1200 × 2400 mm", 100,
     "Rãnh C cách nhiệt", "Gioăng EPDM cách nhiệt 2 lớp / Silicon Dow Corning 795",
     "Anodized tách 2 màu, sơn PVDF, màu champagne phổ biến",
     "Uf < 2.5 W/(m²K), giải pháp nhôm cách nhiệt giá tốt nhất thị trường Việt Nam",
     "Profile mỏng hơn hệ 65, giới hạn kính hộp",
     "✓", "✓", "✓", "✓", "Hoàn thành", 85, "https://nhompag.com.vn", ""),

    ("PG-002", "Cầu cách nhiệt - Cao cấp", "PAG65TB", "PAG", "Việt Nam", "EN 14351-1",
     "Cửa sổ + Cửa đi", "Mở quay + Mở hất (Casement + Tilt-Turn)", "Khung cầu cách nhiệt PA66 GF25",
     "Ngoại thất - Công trình xanh", "Biệt thự, khách sạn, văn phòng LEED Platinum",
     1.8, "Kính hộp Low-E 24-36mm / Kính 3 lớp 44mm", "16mm",
     "1600 × 2800 mm", 150,
     "Rãnh C cách nhiệt cao cấp", "Gioăng EPDM đa khoang cách nhiệt / Silicon Dow Corning",
     "Anodized tách 2 màu trong/ngoài, sơn PVDF 2 thành phần",
     "Uf < 1.8 W/(m²K), chuẩn PAH/PAG tốt nhất thị trường Việt Nam, chống đọng sương",
     "Giá cao, ít nhà phân phối",
     "✓", "✓", "✓", "✓", "Hoàn thành", 85, "https://nhompag.com.vn", ""),

    ("PG-003", "Hàn góc liền khối - Seamless", "PAG Seamless", "PAG", "Việt Nam", "EN 14351-1",
     "Cửa sổ + Cửa đi", "Mở quay (Casement)", "Khung hàn nhiệt liền khối CNC",
     "Ngoại thất cao cấp", "Biệt thự siêu cao cấp, villa resort, phòng trưng bày",
     2.0, "Kính hộp Low-E 24-44mm / Kính 3 lớp", "16mm",
     "1400 × 2800 mm", 150,
     "Rãnh C cách nhiệt đặc biệt", "Gioăng EPDM 4 lớp / Silicon Dow Corning 791",
     "Anodized tách màu siêu mịn - không có vết ghép góc",
     "Góc mối hàn nhiệt liền khối hoàn toàn không vết ghép, thẩm mỹ cực cao, kín tuyệt đối",
     "Yêu cầu máy hàn CNC chuyên dụng, giá cao hơn 30% so với ép góc thông thường",
     "✓", "✓", "✓", "✓", "Hoàn thành", 85, "https://nhompag.com.vn", ""),

    # ============================================================
    # OWIN - VIETNAM (Cửa thủy lực & Trượt quay)
    # ============================================================
    ("OW-001", "Thủy lực - Siêu cao cấp", "Owin HL180", "Owin", "Việt Nam", "TCVN",
     "Cửa đi", "Thủy lực (Hydraulic Pivot)", "Khung siêu nặng + Piston thủy lực",
     "Ngoại thất - Siêu biệt thự", "Biệt thự siêu sang, sảnh khách sạn 5 sao, phòng VIP",
     2.5, "Kính cường lực / laminated 15-22mm", "22mm",
     "5000 × 4000 mm", 1500,
     "Phụ kiện thủy lực Biloba / Floor Spring Dorma TS98", "Keo silicon kết cấu / Gioăng tổng hợp",
     "Anodized ED cao cấp, sơn đặc chủng theo yêu cầu (vàng, đồng, titan)",
     "Cửa siêu rộng một cánh (đến 5m), đóng mở bằng một ngón tay nhờ hệ thủy lực cân bằng",
     "Giá dự án từ 200 triệu đến vài tỷ, yêu cầu gia cố nền sàn đặc biệt",
     "✓", "✓", "✓", "✓", "Hoàn thành", 85, "", ""),

    ("OW-002", "Trượt quay - Cao cấp", "Owin SR", "Owin", "Việt Nam", "TCVN",
     "Cửa đi", "Trượt quay (Sliding Rotating)", "Khung + Cánh + Ray treo trên",
     "Ngoại thất cao cấp", "Biệt thự, nhà phố sang trọng, phòng trưng bày",
     2.0, "Kính cường lực 10-15mm", "15mm",
     "2000 × 3000 mm", 150,
     "Phụ kiện trượt quay Slido Dorma / Häfele", "Gioăng EPDM / Silicon",
     "Anodized ED, sơn tĩnh điện mờ đặc chủng",
     "Không ray dưới sàn, đóng mở 180° trơn tru, thẩm mỹ cao",
     "Trọng tải cánh hạn chế, cần lắp đặt chính xác cao",
     "✓", "✓", "✓", "✓", "Hoàn thành", 80, "", ""),

    # ============================================================
    # TOPAL - VIETNAM
    # ============================================================
    ("TP-001", "Anodized - Phổ thông", "Topal 55", "Topal", "Việt Nam", "TCVN",
     "Cửa đi + Cửa sổ", "Mở quay (Casement)", "Khung + Cánh",
     "Nội thất + Ngoại thất", "Nhà phố, căn hộ",
     1.4, "Kính đơn 5-10mm", "10mm",
     "1200 × 2400 mm", 80,
     "Rãnh 22mm", "Gioăng EPDM / Silicon trung tính",
     "Sơn tĩnh điện đa màu",
     "Giá bình dân, màu sắc đa dạng",
     "Profile mỏng, tải trọng thấp",
     "✓", "✓", "✓", "✓", "Hoàn thành", 75, "", ""),

    ("TP-002", "Anodized - Trung cấp", "Topal 65", "Topal", "Việt Nam", "TCVN",
     "Cửa đi + Cửa sổ", "Mở quay + Trượt lùa", "Khung + Cánh",
     "Ngoại thất", "Biệt thự, nhà phố",
     1.6, "Kính đơn 5-12mm / Kính hộp 20-28mm", "12mm",
     "1600 × 2800 mm", 120,
     "Rãnh C / Rãnh 22", "Gioăng EPDM đa khoang / Silicon Dow Corning",
     "Anodized bạc, sơn tĩnh điện, champagne",
     "Phổ biến miền Nam, đa dạng mẫu mã, giá cạnh tranh",
     "Ít hệ chuyên dụng hơn Civro",
     "✓", "✓", "✓", "✓", "Hoàn thành", 80, "", ""),

    ("TP-003", "Cầu cách nhiệt - Cao cấp", "Topal Prima TB", "Topal", "Việt Nam", "EN 14351-1",
     "Cửa sổ + Cửa đi", "Mở quay + Mở hất", "Khung cầu cách nhiệt PA66",
     "Ngoại thất - Công trình xanh", "Biệt thự cao cấp, công trình xanh",
     1.8, "Kính hộp Low-E 24-36mm", "16mm",
     "1400 × 2800 mm", 150,
     "Rãnh C cách nhiệt", "Gioăng EPDM cách nhiệt / Dow Corning",
     "Anodized tách màu, sơn PVDF",
     "Giải pháp cách nhiệt phổ biến tại TP.HCM và vùng phụ cận",
     "Thị phần nhỏ hơn Civro và PAG ở mảng cách nhiệt",
     "✓", "✓", "✓", "✓", "Hoàn thành", 75, "", ""),

    # ============================================================
    # EUROVN & QUEENVIET - VIETNAM
    # ============================================================
    ("EV-001", "Anodized - Trung cấp", "EuroVN 65", "EuroVN", "Việt Nam", "TCVN",
     "Cửa đi + Cửa sổ", "Mở quay + Trượt lùa", "Khung + Cánh",
     "Ngoại thất", "Biệt thự, nhà phố",
     1.6, "Kính đơn 5-12mm / Kính hộp 20-28mm", "12mm",
     "1600 × 2800 mm", 120,
     "Rãnh C / Rãnh 22", "Gioăng EPDM / Silicon Dow Corning",
     "Anodized, sơn tĩnh điện",
     "Thiết kế Châu Âu giá Việt Nam, phù hợp dự án nhà ở cao cấp",
     "Thị phần nhỏ, phân phối hạn chế",
     "✓", "✓", "✓", "✓", "Hoàn thành", 70, "", ""),

    ("QV-001", "Anodized - Phổ thông", "QueenViet 55", "QueenViet", "Việt Nam", "TCVN",
     "Cửa đi + Cửa sổ", "Mở quay (Casement)", "Khung + Cánh",
     "Nội thất + Ngoại thất", "Nhà phố, căn hộ phổ thông",
     1.4, "Kính đơn 5-10mm", "10mm",
     "1200 × 2400 mm", 80,
     "Rãnh 22mm", "Gioăng EPDM / Silicon",
     "Sơn tĩnh điện đa màu",
     "Giá bình dân, đa dạng màu sắc",
     "Profile mỏng, tải trọng thấp",
     "✓", "✗", "✓", "✓", "Hoàn thành", 65, "", ""),

    # ============================================================
    # YANGLI - VIETNAM (Trung Quốc thiết kế)
    # ============================================================
    ("YL-001", "Anodized - Phổ thông", "Yangli 55", "Yangli", "Trung Quốc/Việt Nam", "GB/T 8478",
     "Cửa đi + Cửa sổ", "Mở quay (Casement)", "Khung + Cánh",
     "Nội thất + Ngoại thất", "Nhà phố, căn hộ, nhà xưởng",
     1.4, "Kính đơn 5-10mm", "10mm",
     "1200 × 2400 mm", 80,
     "Rãnh 22mm", "Gioăng EPDM / Silicon trung tính",
     "Sơn tĩnh điện bột, anodized bạc",
     "Giá cạnh tranh nhất thị trường, chất lượng ổn định ở phân khúc phổ thông",
     "Thẩm mỹ không bằng hệ Châu Âu, phụ kiện phụ thuộc Trung Quốc",
     "✓", "✗", "✓", "✓", "Hoàn thành", 70, "", ""),

    ("YL-002", "Anodized - Trung cấp", "Yangli 65", "Yangli", "Trung Quốc/Việt Nam", "GB/T 8478",
     "Cửa đi + Cửa sổ", "Mở quay + Trượt lùa", "Khung + Cánh",
     "Ngoại thất", "Nhà phố, chung cư cao cấp",
     1.6, "Kính đơn 5-12mm / Kính hộp 20-28mm", "12mm",
     "1600 × 2800 mm", 120,
     "Rãnh C / Rãnh 22", "Gioăng EPDM / Silicon",
     "Anodized bạc, sơn tĩnh điện màu",
     "Giá trung bình, chất lượng khá",
     "Ít lựa chọn về hệ chuyên dụng",
     "✓", "✓", "✓", "✓", "Hoàn thành", 70, "", ""),

    # ============================================================
    # HỆ SLIM - CÁC HÃNG VIỆT NAM VÀ QUỐC TẾ
    # ============================================================
    ("SL-001", "Slim - Nội thất phổ thông", "Slim-I 45", "Nhôm Slim VN (tổng hợp)", "Việt Nam", "TCVN",
     "Cửa đi + Cửa thông phòng", "Trượt lùa giảm chấn (Soft Close Sliding)", "Khung bản mỏng + Cánh kính + Ray ẩn",
     "Nội thất", "Phòng ngủ, phòng vệ sinh, phòng thay đồ, tủ quần áo, văn phòng",
     1.2, "Kính cường lực 8-12mm", "12mm",
     "2000 × 2800 mm", 80,
     "Ray treo Hettich / Häfele / Slido trên trần", "Gioăng mềm đệm nhẹ / không cần keo silicon",
     "Anodized bạc, vàng champagne, đen xước, trắng mờ",
     "Thẩm mỹ cực cao (không thấy ray dưới sàn), giảm chấn tự hãm, lắp đặt nhanh",
     "Chỉ phù hợp nội thất, không chống thấm nước mưa ngoài trời",
     "✓", "✗", "✓", "✓", "Hoàn thành", 85, "", ""),

    ("SL-002", "Slim - Nội thất cao cấp", "Slim-I 70", "Nhôm Slim VN (tổng hợp)", "Việt Nam", "TCVN",
     "Cửa đi + Vách ngăn phòng", "Trượt lùa liên động đa cánh (Multi-panel Sliding)", "Khung bản mỏng + Cánh kính lớn",
     "Nội thất", "Phòng khách lớn, văn phòng open space, phòng hội thảo",
     1.4, "Kính cường lực 10-15mm", "15mm",
     "6000 × 3000 mm", 120,
     "Ray đôi Slido Dorma / Häfele 50 kg", "Gioăng mềm đệm kín cạnh / không keo silicon",
     "Anodized, đen mờ, champagne vàng, đồng antique",
     "Mở toàn bộ vách thông suốt, liên động kéo nhẹ 3-4 cánh cùng lúc",
     "Chỉ nội thất, giá cao theo diện tích kính lớn",
     "✓", "✓", "✓", "✓", "Đang nghiên cứu", 70, "", ""),

    ("SL-003", "Slim - Ngoại thất cao cấp", "Slim-O 60", "Nhôm Slim VN (tổng hợp)", "Việt Nam", "TCVN",
     "Cửa đi", "Trượt lùa ngoại thất (Outdoor Slim Sliding)", "Khung bản mỏng kép + Ray kép chịu lực",
     "Ngoại thất", "Biệt thự, ban công, lối ra sân vườn nhỏ",
     1.6, "Kính cường lực 10-15mm / Kính hộp 20-28mm", "15mm",
     "3000 × 2800 mm", 150,
     "Ray thép cường lực + Bánh xe chịu lực inox", "Gioăng EPDM kín nước / Silicon Dow Corning",
     "Anodized ED, sơn tĩnh điện bột chống UV",
     "Thẩm mỹ ngoại thất profile mỏng, nhìn nhiều kính hơn nhôm",
     "Kín nước kém hơn cửa đi thông thường, giới hạn kích thước nhỏ hơn hệ chuẩn",
     "✓", "✗", "✓", "✓", "Đang nghiên cứu", 65, "", ""),

    ("SL-004", "Slim Steel Look", "Slim Steel Look", "Vitrocsa / Local makers", "Thụy Sĩ/Việt Nam", "EN 12207",
     "Cửa đi + Cửa sổ + Vách kính", "Mở quay + Cố định (Casement + Fixed)", "Khung profile giả thép nghệ thuật",
     "Ngoại thất cao cấp", "Biệt thự phong cách Loft/Industrial, showroom, nhà hàng",
     3.0, "Kính cường lực 10-15mm / Kính hộp 20-28mm", "15mm",
     "3000 × 4000 mm", 200,
     "Phụ kiện ẩn chìm đặc chủng", "Gioăng kín EPDM / Silicon đen",
     "Sơn tĩnh điện đen nhám, đen bóng, sơn giả thép cát mờ",
     "Thẩm mỹ cực cao phong cách công nghiệp, profile đậm nét như khung thép",
     "Giá cao, nặng hơn nhôm thường, ít nhà cung cấp tại Việt Nam",
     "✓", "✗", "✓", "✗", "Đang nghiên cứu", 50, "", ""),

    ("SL-005", "Slim Pocket - Lùa âm tường", "Slim Pocket", "Hệ Pocket tổng hợp", "Châu Âu/Việt Nam", "EN",
     "Cửa đi + Cửa thông phòng", "Trượt âm tường (Pocket Sliding)", "Khung nhỏ + Cánh lùa vào trong tường",
     "Nội thất", "Phòng vệ sinh, tủ quần áo âm, phòng ngủ, bếp",
     1.2, "Kính cường lực 8-12mm / Panel đặc", "12mm",
     "1200 × 2800 mm", 60,
     "Ray treo Barn Door / Slido âm tường Häfele", "Gioăng mềm cạnh / không keo",
     "Anodized bạc, trắng mờ, đen mờ",
     "Tối ưu không gian nội thất, không cần cánh xoay ra phòng",
     "Cần tường đủ dày để lùa vào, không cách âm tốt",
     "✗", "✗", "✓", "✗", "Đang nghiên cứu", 45, "", ""),

    # ============================================================
    # SCHÜCO - GERMANY (Đức - Cao cấp/Siêu cao cấp)
    # ============================================================
    ("SH-001", "Casement - Cao cấp Đức", "AWS 65", "Schüco", "Đức", "EN 14351-1 / EN 12207 Cls 4",
     "Cửa sổ + Cửa đi", "Mở quay (Casement)", "Khung + Cánh cầu cách nhiệt PA66 GF25",
     "Ngoại thất - Công trình xanh", "Biệt thự, khách sạn 5 sao, văn phòng hạng A",
     2.0, "Kính hộp Low-E 24-36mm / Kính 3 lớp 44mm", "18mm",
     "1800 × 3000 mm", 200,
     "Rãnh C Euro Groove - tương thích toàn bộ Roto/Siegenia/Maco/Winkhaus",
     "Gioăng EPDM đa khoang 4 lớp / Silicon Dow Corning 795",
     "Anodized tách màu, sơn PVDF 70%, décor wood-look, RAL đặc chủng",
     "Uf = 1.3 W/(m²K) - top đầu thế giới, cách âm Rw 45dB, bền 50 năm, phụ kiện nguyên bộ Châu Âu",
     "Giá cao hơn hệ Việt Nam 3-5 lần, nhập khẩu dài ngày",
     "✓", "✓", "✓", "✓", "Hoàn thành", 90, "https://www.schueco.com", ""),

    ("SH-002", "Casement - Siêu cao cấp Đức", "AWS 75.SI", "Schüco", "Đức", "EN 14351-1 / Passive House",
     "Cửa sổ + Cửa đi", "Mở quay + Mở hất (Casement + Tilt-Turn)", "Khung cầu cách nhiệt siêu PA66 GF25",
     "Ngoại thất - Passive House", "Nhà thụ động (Passive House), tòa nhà Zero Energy",
     2.0, "Kính 3 lớp 44-52mm / Kính 3 lớp chân không", "20mm",
     "2000 × 3500 mm", 250,
     "Rãnh C Châu Âu đặc biệt", "Gioăng EPDM 5 lớp cách nhiệt cao cấp",
     "Anodized tách màu siêu cao cấp, sơn PVDF 2 lớp",
     "Uf = 0.97 W/(m²K) - đạt Passive House, cách âm Rw 52dB, loại bỏ hoàn toàn cầu nhiệt",
     "Giá cực cao, thị trường Việt Nam rất hạn chế",
     "✓", "✓", "✓", "✓", "Đang nghiên cứu", 60, "https://www.schueco.com", ""),

    ("SH-003", "Lift & Slide - Đức siêu cao cấp", "ASS 77 PD.HI", "Schüco", "Đức", "EN 13830 / EN 12208",
     "Cửa đi", "Trượt nâng cách nhiệt (Lift & Slide Thermal)", "Khung cầu cách nhiệt + Cánh nặng Lift Slide",
     "Ngoại thất - Siêu biệt thự", "Penthouse, biệt thự siêu sang, resort 6 sao",
     2.5, "Kính 3 lớp 48-60mm", "22mm",
     "10000 × 3500 mm", 800,
     "Phụ kiện Schüco AvanTec đặc chủng", "Gioăng EPDM cầu cách nhiệt 5 lớp",
     "Anodized, sơn PVDF 70%, gỗ ốp mặt trong theo yêu cầu",
     "Mở rộng nhất thế giới (đến 10m), cách nhiệt kép, Uf < 1.5 W/(m²K)",
     "Giá dự án từ 2-10 tỷ VND/bộ, thi công siêu phức tạp",
     "✓", "✓", "✓", "✓", "Đang nghiên cứu", 55, "https://www.schueco.com", ""),

    ("SH-004", "Sliding - Đức cao cấp", "ADS 70.HI", "Schüco", "Đức", "EN 12207 / EN 12208",
     "Cửa đi", "Trượt lùa (Sliding)", "Khung + Cánh + Ray đặc biệt",
     "Ngoại thất", "Biệt thự, văn phòng cao cấp",
     2.0, "Kính hộp 24-40mm", "18mm",
     "6000 × 2800 mm", 400,
     "Phụ kiện Schüco AvanTec Slide", "Gioăng EPDM 4 lớp cách nhiệt",
     "Anodized, sơn PVDF",
     "Uf = 1.3 W/(m²K), cách âm Rw 44dB, bền vững cao",
     "Giá nhập khẩu cao, thi công chuyên nghiệp",
     "✓", "✓", "✓", "✓", "Đang nghiên cứu", 55, "https://www.schueco.com", ""),

    ("SH-005", "Curtain Wall - Đức cao cấp", "FW 50+", "Schüco", "Đức", "EN 13830 / CWCT",
     "Vách mặt dựng", "Cố định (Fixed - Stick/Unitized)", "Module đố đứng đố ngang kết cấu",
     "Ngoại thất - Mặt dựng", "Tòa nhà văn phòng hạng A, khách sạn quốc tế",
     2.5, "Kính hộp 24-50mm / Kính 3 lớp 60mm", "50mm",
     "Không giới hạn", 1000,
     "Hệ Stick + Unitized Schüco AvanTec CW", "Silicon kết cấu Dow Corning 983 / Sika Sikasil SG-500",
     "Anodized, PVDF 70% AkzoNobel, mill finish",
     "Tiêu chuẩn tòa nhà thế giới, bền 60 năm, thiết kế tối ưu tải gió động đất",
     "Giá nhập khẩu cực cao, cần tư vấn kỹ thuật Đức",
     "✓", "✓", "✓", "✓", "Đang nghiên cứu", 60, "https://www.schueco.com", ""),

    # ============================================================
    # REYNAERS - BELGIUM (Bỉ - Cao cấp)
    # ============================================================
    ("RY-001", "Casement - Bỉ cao cấp", "CS 60", "Reynaers", "Bỉ", "EN 14351-1 / EN 12207",
     "Cửa sổ + Cửa đi", "Mở quay + Mở hất (Casement + Tilt-Turn)", "Khung + Cánh cầu cách nhiệt PA66",
     "Ngoại thất - Công trình xanh", "Biệt thự, khách sạn 5 sao, văn phòng cao cấp",
     1.8, "Kính hộp Low-E 24-36mm / Kính 3 lớp 44mm", "16mm",
     "1800 × 3000 mm", 180,
     "Rãnh C Euro Groove", "Gioăng EPDM đa khoang 3 lớp / Silicon Dow Corning",
     "Anodized tách màu, sơn PVDF 70%, RAL màu sắc đầy đủ",
     "Uf = 1.5 W/(m²K), hệ phụ kiện Châu Âu đầy đủ, thiết kế Bỉ sang trọng",
     "Giá nhập khẩu cao, giao hàng lâu",
     "✓", "✓", "✓", "✓", "Đang nghiên cứu", 65, "https://www.reynaers.com", ""),

    ("RY-002", "Casement - Bỉ siêu cao cấp", "CS 77", "Reynaers", "Bỉ", "EN 14351-1 / Passive",
     "Cửa sổ + Cửa đi", "Mở quay + Mở hất (Casement + Tilt-Turn)", "Khung cầu cách nhiệt cao cấp",
     "Ngoại thất - Passive House", "Biệt thự siêu sang, công trình Zero Energy",
     2.0, "Kính 3 lớp 44-56mm", "20mm",
     "2000 × 3500 mm", 250,
     "Rãnh C Châu Âu siêu cao cấp", "Gioăng EPDM 5 lớp cách nhiệt",
     "Anodized 2 màu trong ngoài, sơn PVDF 2 lớp cao cấp",
     "Uf = 1.0 W/(m²K), đạt Passive House chuẩn Bỉ, cách âm 48dB",
     "Giá cực cao, thị trường Việt Nam rất hạn chế",
     "✓", "✓", "✓", "✓", "Đang nghiên cứu", 50, "https://www.reynaers.com", ""),

    ("RY-003", "Lift & Slide - Bỉ cao cấp", "CP 155-LS", "Reynaers", "Bỉ", "EN 13830",
     "Cửa đi", "Trượt nâng (Lift & Slide)", "Khung + Cánh cách nhiệt + Ray đặc biệt",
     "Ngoại thất - Siêu biệt thự", "Biệt thự cao cấp, penthouse Châu Âu",
     2.5, "Kính 3 lớp 44-56mm", "20mm",
     "8000 × 3200 mm", 600,
     "Phụ kiện Reynaers LSS đặc chủng", "Gioăng EPDM cầu cách nhiệt 4 lớp",
     "Anodized tách màu cao cấp, sơn PVDF",
     "Uf < 1.5 W/(m²K), Lift Slide cách nhiệt chuẩn Bỉ hàng đầu thế giới",
     "Nhập khẩu dài ngày, giá cực cao",
     "✓", "✓", "✓", "✓", "Đang nghiên cứu", 50, "https://www.reynaers.com", ""),

    ("RY-004", "Curtain Wall - Bỉ", "CW 50", "Reynaers", "Bỉ", "EN 13830",
     "Vách mặt dựng", "Cố định (Stick/Unitized)", "Module đố đứng đố ngang",
     "Ngoại thất - Mặt dựng", "Tòa nhà cao tầng châu Âu",
     2.0, "Kính hộp 24-48mm", "48mm",
     "Không giới hạn", 1000,
     "Hệ Stick/Unitized Reynaers", "Silicon kết cấu Dow Corning / Sika",
     "Anodized, PVDF, mill finish",
     "Tiêu chuẩn Châu Âu, bền 50 năm, tải gió tối ưu",
     "Nhập khẩu, giá cao",
     "✓", "✓", "✓", "✓", "Đang nghiên cứu", 50, "https://www.reynaers.com", ""),

    # ============================================================
    # XINGFA - CHINA (Trung Quốc - Phổ thông đến Trung cấp)
    # ============================================================
    ("XF-001", "Casement - Trung Quốc phổ thông", "Xingfa 55", "Xingfa", "Trung Quốc", "GB/T 8478",
     "Cửa sổ + Cửa đi", "Mở quay (Casement)", "Khung + Cánh",
     "Nội thất + Ngoại thất", "Nhà phố, căn hộ phổ thông",
     1.4, "Kính đơn 5-10mm", "10mm",
     "1200 × 2200 mm", 80,
     "Rãnh 22mm", "Gioăng EPDM / Silicon trung tính",
     "Anodized bạc, sơn tĩnh điện bột",
     "Giá cực cạnh tranh, nguồn hàng dồi dào",
     "Chất lượng không đồng đều tùy lô hàng, hệ thống hậu mãi hạn chế",
     "✓", "✗", "✓", "✓", "Hoàn thành", 65, "https://www.xingfa-alu.com", ""),

    ("XF-002", "Casement - Trung Quốc trung cấp", "Xingfa 65", "Xingfa", "Trung Quốc", "GB/T 8478",
     "Cửa sổ + Cửa đi", "Mở quay + Trượt lùa", "Khung + Cánh",
     "Ngoại thất", "Nhà phố, chung cư trung cấp",
     1.6, "Kính đơn 5-12mm / Kính hộp 20-28mm", "12mm",
     "1600 × 2800 mm", 120,
     "Rãnh C / Rãnh 22", "Gioăng EPDM / Silicon",
     "Anodized, sơn tĩnh điện",
     "Giá tốt, chất lượng ổn hơn hệ 55",
     "Không phải hệ Châu Âu, phụ kiện phụ thuộc TQ",
     "✓", "✗", "✓", "✓", "Hoàn thành", 65, "https://www.xingfa-alu.com", ""),

    ("XF-003", "Lift & Slide - Trung Quốc", "Xingfa LS90", "Xingfa", "Trung Quốc", "GB/T",
     "Cửa đi", "Trượt nâng (Lift & Slide)", "Khung + Cánh + Ray đặc biệt",
     "Ngoại thất", "Biệt thự tầm trung, nhà phố cao cấp",
     1.8, "Kính cường lực 10-15mm / Kính hộp 20-32mm", "15mm",
     "5000 × 2800 mm", 300,
     "Rãnh C / Phụ kiện OPK hoặc Hopo", "Gioăng EPDM / Silicon",
     "Anodized, sơn tĩnh điện",
     "Giá cạnh tranh cho hệ Lift Slide, vận hành êm",
     "Chất lượng kiểm soát kém hơn Châu Âu",
     "✓", "✗", "✓", "✓", "Đang nghiên cứu", 60, "https://www.xingfa-alu.com", ""),

    # ============================================================
    # CÁC HỆ CHUYÊN DỤNG BỔ SUNG
    # ============================================================
    ("SP-001", "Cửa xoay trục - Pivot", "Pivot Door Standard", "Các hãng (Civro/VR/Owin)", "Việt Nam", "TCVN",
     "Cửa đi", "Xoay trục (Pivot)", "Cánh xoay trục giữa + Trục pivot sàn trần",
     "Ngoại thất", "Biệt thự siêu cao cấp, sảnh resort, showroom",
     2.0, "Kính cường lực 15-22mm", "22mm",
     "2000 × 4000 mm", 500,
     "Phụ kiện pivot inox SUS316 DORMA / FritsJurgens / Biloba", "Gioăng cạnh kín / Silicon kết cấu",
     "Anodized ED, sơn RAL đặc chủng",
     "Thẩm mỹ cực cao, mở 180° tinh tế, cánh siêu rộng một tấm kính nguyên",
     "Cần tính toán tải trọng kỹ, giá cao, thi công phức tạp",
     "✓", "✗", "✓", "✗", "Đang nghiên cứu", 55, "", ""),

    ("SP-002", "Cửa xếp trượt - Bi-fold", "Bi-fold Standard", "Civro / Maxpro / Soco", "Việt Nam", "EN",
     "Cửa đi", "Xếp trượt (Bi-fold / Folding)", "Cánh xếp gấp + Bản lề xếp + Ray trên",
     "Ngoại thất", "Nhà hàng, quán cà phê, biệt thự, lối ra sân",
     1.8, "Kính cường lực 8-12mm", "12mm",
     "5000 × 2800 mm", 40,
     "Phụ kiện Roto Fold / OPK Bi-fold / Hopo", "Gioăng EPDM đường viền / Silicon",
     "Sơn tĩnh điện, anodized, champagne",
     "Mở toàn bộ không gian, xếp gọn về một phía, phù hợp nhà hàng mở",
     "Kín khít kém nhất trong các hệ cửa, mỗi cánh tải trọng giới hạn",
     "✓", "✗", "✓", "✓", "Đang nghiên cứu", 60, "", ""),

    ("SP-003", "Cửa tự động - Auto Sliding", "Auto Sliding Standard", "Dorma / Besam / Local", "Đức/Việt Nam", "EN 16005",
     "Cửa đi", "Tự động trượt (Auto Sliding)", "Khung + Cánh kính + Cảm biến mắt thần",
     "Thương mại", "Siêu thị, trung tâm thương mại, bệnh viện, khách sạn sảnh lớn",
     1.6, "Kính an toàn laminated 8-12mm", "12mm",
     "3000 × 2800 mm", 150,
     "Hệ truyền động cơ AC / DC + Ray dẫn hướng", "Gioăng mềm / Màn quét không chạm",
     "Anodized bạc, anodized đen, sơn tĩnh điện",
     "Vận hành hoàn toàn tự động, tiện lợi cho người đi tay bận hoặc xe lăn",
     "Cần bảo trì cảm biến và động cơ định kỳ, tốn điện",
     "✓", "✗", "✓", "✓", "Đang nghiên cứu", 55, "", ""),

    ("SP-004", "Cửa chống cháy - Fire Rated", "Fire Door 60/90", "Hệ chuyên dụng", "Việt Nam/Nhật", "TCVN 9374 / EN 1634",
     "Cửa đi", "Mở quay (Fire Rated Casement)", "Khung thép + Cánh nhôm/thép chống cháy",
     "An toàn PCCC", "Hành lang thoát hiểm, buồng thang bộ, phòng kỹ thuật",
     2.0, "Kính chống lửa 30-90 phút (Fire Glass)", "25mm",
     "1200 × 2400 mm", 100,
     "Bản lề chống cháy + Cưỡng bức đóng Fire Door Closer", "Gioăng bảo ôn tự trương nở khi cháy",
     "Sơn tĩnh điện bột chịu nhiệt, sơn chống cháy Intumescent",
     "Ngăn lan cháy theo EI60/EI90, bắt buộc theo QCVN 06, tuổi thọ 30 năm",
     "Chỉ phù hợp lắp nơi thoát hiểm, không dùng cho trang trí",
     "✓", "✓", "✓", "✓", "Đang nghiên cứu", 55, "", ""),

    ("SP-005", "Mái kính - Skylight", "Skylight Standard", "Soco / Local makers", "Việt Nam", "TCVN",
     "Mái kính", "Cố định / Mở nghiêng (Fixed / Vented Skylight)", "Khung nhôm chống thấm + Kính nghiêng",
     "Mái công trình", "Giếng trời biệt thự, mái hành lang, sảnh TTTM",
     2.0, "Kính cường lực laminated 10-15mm / Kính hộp Low-E", "15mm",
     "Không giới hạn (theo thiết kế)", 200,
     "Hệ thanh đỡ mái nhôm đặc chủng", "Silicon kết cấu + Silicon chống thấm dốc mái",
     "Anodized, sơn bột chịu UV",
     "Đưa ánh sáng tự nhiên vào sâu trong nhà, tiết kiệm điện chiếu sáng",
     "Cần thiết kế thoát nước mưa kỹ lưỡng, vệ sinh định kỳ",
     "✓", "✗", "✓", "✓", "Đang nghiên cứu", 55, "", ""),

    ("SP-006", "Lan can kính - Glass Railing", "Glass Railing Frameless", "Maxpro / Owin / Local", "Việt Nam", "TCVN 9392",
     "Lan can", "Cố định (Fixed Glass Railing)", "Đế chân âm sàn + Kính cường lực đứng",
     "Nội thất + Ngoại thất", "Ban công biệt thự, cầu thang nội thất, hành lang cao tầng",
     3.0, "Kính cường lực đứng 12-19mm / Kính laminated 10+10mm", "19mm",
     "Không giới hạn (theo thiết kế)", 80,
     "Đế âm sàn inox SUS304/316 + Thanh nhôm đỡ trên", "Keo silicon kết cấu đế kính",
     "Anodized bạc, inox bóng, đen mờ",
     "Không gian mở, ánh sáng xuyên suốt, thẩm mỹ hiện đại",
     "Cần bảo trì mối kết cấu kính, dễ bám bẩn, cần lau định kỳ",
     "✓", "✗", "✓", "✓", "Đang nghiên cứu", 55, "", ""),

    ("SP-007", "Pergola nhôm - Motorized", "Pergola Louvered", "Local manufacturers", "Việt Nam/Ý", "TCVN",
     "Mái kính + Pergola", "Lá chớp xoay tự động (Motorized Louvers)", "Khung nhôm + Lá chớp xoay góc",
     "Ngoại thất", "Biệt thự sân vườn, nhà hàng ngoài trời, resort",
     2.5, "Không sử dụng kính (lá chớp nhôm đặc)", "N/A",
     "Không giới hạn (theo thiết kế)", 50,
     "Hệ truyền động cơ AC bánh răng + Remote điều khiển", "Gioăng cao su EPDM kín nước",
     "Anodized ED, sơn tĩnh điện bột chịu UV, màu RAL",
     "Điều tiết ánh sáng và mưa tự động bằng remote hoặc cảm biến mưa, che nắng hoàn hảo",
     "Giá cao, cần bảo trì mô tơ định kỳ, điện tiêu thụ",
     "✓", "✗", "✓", "✓", "Đang nghiên cứu", 50, "", ""),

    ("SP-008", "Vách ngăn văn phòng - Office Partition", "Office Partition 80", "Các hãng local", "Việt Nam", "TCVN",
     "Vách ngăn", "Cố định + Cửa trượt (Fixed + Sliding)", "Profile vách ngăn kính mỏng",
     "Nội thất", "Văn phòng, phòng họp, phòng làm việc, khu coworking",
     1.2, "Kính cường lực 10-12mm hoặc kính đục mờ", "12mm",
     "Không giới hạn (theo thiết kế)", 60,
     "Phụ kiện trượt văn phòng Häfele / Hettich", "Gioăng cạnh mềm / keo silicon nội thất",
     "Anodized bạc, đen mờ, champagne vàng, trắng mờ",
     "Phân chia không gian linh hoạt, ánh sáng xuyên qua kính, thẩm mỹ hiện đại",
     "Cách âm kém hơn tường xây, chỉ nội thất",
     "✓", "✗", "✓", "✓", "Đang nghiên cứu", 50, "", ""),

    ("SP-009", "Cửa thông phòng - Barn Door", "Barn Door Rail", "Häfele / Hettich / Local", "Đức/Việt Nam", "TCVN",
     "Cửa đi nội thất", "Treo thanh ngang (Barn Door Sliding)", "Thanh ray treo + Cánh phẳng/kính",
     "Nội thất", "Phòng ngủ, bếp mở, phòng thư, nhà kho",
     1.0, "Kính cường lực 8-10mm / Gỗ MDF / Panel thép", "10mm",
     "1500 × 2800 mm", 80,
     "Ray Barn Door Häfele / Gedore 80kg / 150kg", "Gioăng cạnh mềm nhỏ (nếu cần)",
     "Sơn tĩnh điện, gỗ công nghiệp, kết hợp kim loại",
     "Trang trí đẹp phong cách công nghiệp/rustic, không cần diện tích xoay cánh",
     "Không kín hoàn toàn, không cách âm tốt",
     "✗", "✗", "✓", "✗", "Đang nghiên cứu", 40, "", ""),

    ("SP-010", "Cửa chống đạn - Bullet Resistant", "Bullet Resistant Level 3", "Hệ chuyên dụng", "Đức/Mỹ", "EN 1063 / UL 752",
     "Cửa đi", "Mở quay (Bullet Resistant Casement)", "Khung nhôm đặc biệt + Tấm thép gia cố",
     "An ninh", "Ngân hàng, phòng VIP, đại sứ quán, phòng máy chủ",
     3.0, "Kính chống đạn Lexan / Pilkington Protect BR6 25-50mm", "50mm",
     "1200 × 2400 mm", 300,
     "Phụ kiện an ninh khóa đặc chủng", "Gioăng cao su chịu lực",
     "Sơn thép + anodized nhôm",
     "Chịu đạn đến cấp BR3/BR6, hội tụ chức năng an ninh và thẩm mỹ",
     "Giá rất cao, nhập khẩu, ít đơn vị thi công tại Việt Nam",
     "✗", "✗", "✓", "✗", "Đang nghiên cứu", 35, "", ""),

    # ============================================================
    # YKK AP - JAPAN (Nhật Bản)
    # ============================================================
    ("YK-001", "Casement - Nhật Bản", "YKK WS55", "YKK AP", "Nhật Bản", "JIS A 4702 / JIS A 4706",
     "Cửa sổ + Cửa đi", "Mở quay + Mở hất (Casement + Awning)", "Khung + Cánh đặc chủng Nhật",
     "Ngoại thất", "Biệt thự, chung cư cao cấp Nhật Bản và Việt Nam",
     1.6, "Kính đơn 5-12mm / Kính hộp 20-28mm", "12mm",
     "1600 × 2800 mm", 150,
     "Rãnh C / Phụ kiện YKK nguyên bộ Nhật", "Gioăng EPDM Nhật tiêu chuẩn JIS",
     "Anodized Nhật bạc tự nhiên, sơn bột Nhật chất lượng cao",
     "Kiểm soát chất lượng chuẩn Nhật, độ bền vượt trội, thẩm mỹ tinh tế",
     "Giá cao hơn hàng Việt 2-3 lần, phân phối hạn chế",
     "✓", "✓", "✓", "✓", "Đang nghiên cứu", 65, "https://www.ykkap.co.jp", ""),

    ("YK-002", "Sliding - Nhật Bản", "YKK SL90", "YKK AP", "Nhật Bản", "JIS A 4706",
     "Cửa đi", "Trượt lùa (Sliding)", "Khung + Cánh + Ray inox Nhật",
     "Ngoại thất", "Biệt thự, chung cư cao cấp",
     1.8, "Kính cường lực 10-15mm / Kính hộp 20-28mm", "15mm",
     "4000 × 2400 mm", 200,
     "Ray inox SUS304 tiêu chuẩn Nhật", "Gioăng EPDM Nhật tiêu chuẩn",
     "Anodized Nhật, sơn bột Nhật",
     "Trượt cực êm theo tiêu chuẩn JIS Nhật, bánh xe chịu tải cao",
     "Giá cao, phân phối hạn chế tại Việt Nam",
     "✓", "✓", "✓", "✓", "Đang nghiên cứu", 60, "https://www.ykkap.co.jp", ""),

    # ============================================================
    # TECHNAL - FRANCE (Pháp - Cao cấp)
    # ============================================================
    ("TC-001", "Casement - Pháp cao cấp", "Technal Pylon 45", "Technal", "Pháp", "EN 14351-1",
     "Cửa sổ + Cửa đi", "Mở quay + Mở hất", "Khung cầu cách nhiệt Technal đặc chủng",
     "Ngoại thất", "Dự án kiến trúc cao cấp Châu Âu",
     1.8, "Kính hộp Low-E 24-36mm", "16mm",
     "1600 × 3000 mm", 180,
     "Rãnh C Châu Âu Pháp", "Gioăng EPDM 3 lớp / Silicon Dow Corning",
     "Anodized tách màu, PVDF 70%",
     "Uf = 1.5 W/(m²K), thiết kế Pháp tinh tế, profile thanh lịch nhất trong dòng Châu Âu",
     "Ít phổ biến tại Việt Nam, giá nhập khẩu cao",
     "✓", "✓", "✓", "✓", "Đang nghiên cứu", 45, "https://www.technal.com", ""),

    ("TC-002", "Curtain Wall - Pháp", "Technal Unival CW", "Technal", "Pháp", "EN 13830",
     "Vách mặt dựng", "Cố định (Stick/Unitized Pháp)", "Module CW Technal đặc chủng",
     "Ngoại thất - Mặt dựng", "Tòa nhà cao tầng thiết kế kiến trúc Châu Âu",
     2.0, "Kính hộp 24-48mm", "48mm",
     "Không giới hạn", 1000,
     "Hệ Technal Stick/Unitized", "Silicon kết cấu Dow Corning / Sika",
     "Anodized, PVDF 70%",
     "Thiết kế chuẩn kiến trúc Pháp, linh hoạt định hình công trình biểu tượng",
     "Nhập khẩu giá cao, ít phổ biến tại Việt Nam",
     "✓", "✓", "✓", "✓", "Đang nghiên cứu", 40, "https://www.technal.com", ""),

    # ============================================================
    # ALUPROF - POLAND (Ba Lan - Trung-Cao cấp)
    # ============================================================
    ("AP-001", "Casement - Ba Lan", "Aluprof MB-70", "Aluprof", "Ba Lan", "EN 14351-1",
     "Cửa sổ + Cửa đi", "Mở quay + Mở hất (Casement + Tilt-Turn)", "Khung cầu cách nhiệt",
     "Ngoại thất", "Dự án nhà ở và thương mại Đông Âu và Việt Nam",
     1.8, "Kính hộp Low-E 24-36mm / Kính 3 lớp 44mm", "18mm",
     "1800 × 3000 mm", 200,
     "Rãnh C Euro Groove", "Gioăng EPDM 3 lớp / Silicon Dow Corning",
     "Anodized, sơn PVDF",
     "Uf = 1.5 W/(m²K), chi phí thấp hơn Schüco và Reynaers 20-30%, chất lượng tương đương",
     "Ít phổ biến tại Việt Nam so với Đức và Bỉ",
     "✓", "✓", "✓", "✓", "Đang nghiên cứu", 45, "https://www.aluprof.eu", ""),

    # ============================================================
    # WICONA - GERMANY (Đức - Cao cấp hệ thống tòa nhà)
    # ============================================================
    ("WC-001", "Curtain Wall - Đức công nghiệp", "WICTEC 50", "WICONA", "Đức", "EN 13830 / CWCT",
     "Vách mặt dựng", "Cố định (Stick System WICONA)", "Module WICONA đặc chủng",
     "Ngoại thất - Tòa nhà công nghiệp", "Tòa nhà công nghiệp, nhà máy, nhà kho cao cấp",
     2.5, "Kính hộp 24-48mm", "48mm",
     "Không giới hạn", 1000,
     "Hệ WICONA Stick", "Silicon kết cấu Dow Corning",
     "Anodized, mill finish",
     "Tiêu chuẩn Đức bền vững, phù hợp dự án công nghiệp quy mô lớn",
     "Nhập khẩu giá cao, ít phổ biến tại Việt Nam",
     "✓", "✓", "✓", "✓", "Đang nghiên cứu", 40, "https://www.wicona.com", ""),

    # ============================================================
    # CÁC HỆ ĐẶC BIỆT VÀ HỆ TƯƠNG LAI
    # ============================================================
    ("FT-001", "Smart Door - Cửa thông minh", "Smart Fingerprint Door", "Hệ Smart tổng hợp", "Việt Nam", "TCVN",
     "Cửa đi", "Mở quay (Casement + Smart Lock)", "Khung + Cánh + Module điện tử",
     "Ngoại thất", "Nhà thông minh (Smart Home), biệt thự, căn hộ",
     1.8, "Kính cường lực 10-12mm", "12mm",
     "1200 × 2800 mm", 120,
     "Khóa vân tay + Face ID + Động cơ DC điều khiển từ xa",
     "Gioăng EPDM / Silicon + module chống nước điện tử IP54",
     "Anodized bạc, champagne, đen mờ",
     "Mở khóa bằng vân tay/khuôn mặt/điện thoại, tích hợp hệ thống nhà thông minh",
     "Cần nguồn điện dự phòng pin, chi phí lắp đặt cao hơn",
     "✗", "✗", "✓", "✗", "Đang nghiên cứu", 40, "", ""),

    ("FT-002", "Smart Glass Partition", "Smart Glass / Electrochromic", "AGC / Saint-Gobain", "Bỉ/Pháp", "EN",
     "Vách ngăn", "Cố định (Fixed Smart Glass)", "Khung nhôm + Kính điện biến màu",
     "Nội thất cao cấp", "Phòng họp, phòng VIP, phòng khách sạn 5 sao",
     1.2, "Kính điện biến màu (Smart Glass) 10-12mm", "12mm",
     "3000 × 3000 mm", 60,
     "Hệ điện 110V/220V 50Hz kết nối kính điện tử", "Keo silicon kết dính đặc chủng",
     "Anodized bạc/đen + Kính điện biến đục/trong theo công tắc điện",
     "Điều tiết ánh sáng và riêng tư bằng công tắc điện, thẩm mỹ công nghệ cao",
     "Giá cực cao, kính dễ bị hỏng mạch điện, cần bảo hành chính hãng",
     "✗", "✗", "✓", "✗", "Đang nghiên cứu", 30, "", ""),

    ("FT-003", "Canopy Nhôm", "Aluminum Canopy", "Local manufacturers", "Việt Nam", "TCVN",
     "Mái che + Canopy", "Cố định (Fixed Canopy)", "Khung nhôm thanh profine + Tấm Polycarbonate/kính",
     "Ngoại thất", "Sảnh đón, lối vào biệt thự, nhà hàng, cửa hàng",
     2.0, "PC trong suốt 10mm / Kính cường lực 8-10mm", "10mm",
     "Không giới hạn (theo thiết kế)", 100,
     "Hệ Stick nhôm đặc chủng", "Silicon Dow Corning chống thấm + Vít inox SUS304",
     "Anodized, sơn tĩnh điện bột, champagne, đen",
     "Che nắng mưa sảnh đón, thẩm mỹ ngoại thất đẹp, lắp đặt nhanh",
     "Cần thiết kế thoát nước mái, tải trọng tuyết/gió cần tính toán",
     "✓", "✗", "✓", "✓", "Đang nghiên cứu", 55, "", ""),

    ("FT-004", "Sunroom - Phòng kính ngoài trời", "Sunroom Aluminum", "Local + European brands", "Châu Âu/Việt Nam", "EN",
     "Vách + Mái", "Vách cố định + Mái nghiêng (Sunroom / Garden Room)", "Khung nhôm + Vách kính + Mái kính",
     "Ngoại thất", "Biệt thự sân vườn, resort, nhà hàng garden",
     2.0, "Kính hộp Low-E 24-36mm (vách) / Kính chống nóng mái 10-15mm", "15mm",
     "Không giới hạn (theo thiết kế)", 200,
     "Hệ Stick nhôm đặc chủng cho Sunroom", "Silicon kết cấu + Keo chống thấm mái",
     "Anodized, sơn PVDF, màu RAL trắng/champagne/đen",
     "Tạo không gian kết nối trong/ngoài trời quanh năm, lọc UV và chắn mưa",
     "Nhiệt độ bên trong cao nếu không thiết kế thông gió và che nắng tốt",
     "✓", "✗", "✓", "✓", "Đang nghiên cứu", 45, "", ""),

    ("FT-005", "Curtain Wall Unitized", "UCW System", "Soco / Maxpro / Civro", "Việt Nam", "EN 13830 / AAMA 501",
     "Vách mặt dựng", "Panel đúc sẵn (Unitized Panel)", "Panel hoàn chỉnh đúc sẵn + Kính",
     "Ngoại thất - Tòa nhà cao tầng", "Tòa nhà văn phòng hạng A, khách sạn 5 sao 30+ tầng",
     2.5, "Kính hộp Low-E 28-48mm / Kính 3 lớp 60mm", "48mm",
     "Không giới hạn (theo module)", 1000,
     "Hệ Unitized panel hoàn chỉnh lắp bằng cần trục", "Silicon kết cấu kín nước chuẩn AAMA",
     "Anodized, PVDF 70%, sơn đặc chủng theo dự án",
     "Thi công nhanh (3-4 ngày/tầng), chất lượng đồng đều chuẩn xưởng, lý tưởng cho tòa nhà cao tầng",
     "Chi phí mold cao, không linh hoạt sửa đổi tại công trường",
     "✓", "✓", "✓", "✓", "Đang nghiên cứu", 65, "", ""),

    ("FT-006", "Curtain Wall Spider", "Spider Glass Facade", "Hệ chuyên dụng", "Đức/Việt Nam", "EN 13830",
     "Vách mặt dựng đặc biệt", "Cố định mặt dựng kính điểm (Spider Connector)", "Khung kết cấu thép ẩn + Cần nhện inox",
     "Ngoại thất - Công trình biểu tượng", "Sảnh khách sạn, trung tâm hội nghị, công trình biểu tượng",
     0.0, "Kính cường lực đặc biệt 15-22mm có lỗ khoan cán", "22mm",
     "Không giới hạn (theo thiết kế kết cấu)", 2000,
     "Cần nhện inox SUS316 Spider Point Fitting 4 cánh", "Silicon kết cấu Dow Corning 895",
     "Kính tráng Low-E / Kính in màu kỹ thuật số (Print Glass)",
     "Tối ưu thẩm mỹ mặt kính thuần túy, không thấy frame nhôm, nhìn trong suốt hoàn toàn",
     "Yêu cầu kết cấu thép phụ chịu lực phức tạp, thi công chuyên nghiệp, giá cực cao",
     "✓", "✗", "✓", "✗", "Đang nghiên cứu", 40, "", ""),

    ("FT-007", "Hospital Door - Cửa bệnh viện", "Hospital Hygienic Door", "Hệ chuyên dụng", "Việt Nam/Đức", "EN 1670",
     "Cửa đi bệnh viện", "Tự động trượt + Kháng khuẩn", "Khung nhôm kháng khuẩn + Cửa plastic laminate",
     "Y tế", "Phòng phẫu thuật, ICU, phòng sạch bệnh viện, phòng X-quang",
     2.0, "Kính laminated kháng khuẩn 8-10mm / Panel PVC kháng khuẩn", "10mm",
     "1200 × 2400 mm", 80,
     "Hệ truyền động vô khuẩn (clean room motor)", "Gioăng kín kháng khuẩn không kẽ hở",
     "Sơn Interpon kháng khuẩn + xử lý bề mặt đặc chủng y tế",
     "Đáp ứng yêu cầu vệ sinh vô khuẩn, tự đóng không chạm tay, đạt tiêu chuẩn phòng sạch",
     "Chỉ phù hợp y tế, giá cao hơn cửa thông thường",
     "✓", "✗", "✓", "✓", "Đang nghiên cứu", 40, "", ""),

    ("FT-008", "Tilt-Turn - Mở lật/Mở quay", "Tilt-Turn Window", "Civro / PAG / Schüco", "Châu Âu/VN", "EN 14351-1",
     "Cửa sổ + Cửa đi", "Mở quay + Mở lật (Casement + Tilt-Turn)", "Khung + Cánh mở lật đa vị trí",
     "Ngoại thất", "Căn hộ chung cư cao tầng, văn phòng an toàn",
     1.8, "Kính hộp Low-E 24-36mm", "16mm",
     "1400 × 2600 mm", 120,
     "Rãnh C Euro Groove tương thích Roto/Winkhaus tilt-turn",
     "Gioăng EPDM đa khoang / Silicon Dow Corning",
     "Anodized, sơn PVDF",
     "Tilt (nghiêng lật hé thông gió) hoặc Turn (quay vào trong lau kính dễ dàng), an toàn không rơi kính",
     "Phụ kiện đắt hơn casement thông thường, cần thợ có kinh nghiệm về hệ lật",
     "✓", "✓", "✓", "✓", "Đang nghiên cứu", 65, "", ""),

    ("FT-009", "Corner Slim - Góc không trụ", "Corner Slim Zero Post", "Vitrocsa / Local high end", "Thụy Sĩ/Việt Nam", "EN",
     "Cửa đi + Cửa sổ góc", "Cố định + Mở quay (Corner Fixed + Casement)", "Khung góc không trụ giữa",
     "Ngoại thất siêu cao cấp", "Biệt thự siêu sang, penthouse góc tòa nhà",
     3.0, "Kính cường lực 12-19mm / Kính hộp Low-E", "19mm",
     "3000 × 3500 mm", 300,
     "Phụ kiện bản lề góc không trụ đặc chủng", "Silicon kết cấu kín góc / Gioăng góc mềm",
     "Anodized ED cao cấp, sơn RAL theo yêu cầu",
     "Kính góc không có trụ giữa nhìn 180° toàn cảnh, thẩm mỹ đỉnh cao của kiến trúc kính",
     "Giá cực cao, thiết kế kết cấu phức tạp, rất ít công ty làm được tại Việt Nam",
     "✗", "✗", "✓", "✗", "Đang nghiên cứu", 35, "", ""),

    ("FT-010", "Curtain Wall Cable Facade", "Cable Facade System", "Hệ chuyên dụng", "Đức", "EN 13830",
     "Vách mặt dựng dây căng", "Cố định kính điểm dây căng (Cable Tensile Facade)", "Hệ cáp inox + Cần nhện kính",
     "Ngoại thất - Công trình nghệ thuật", "Công trình biểu tượng, sân bay, trung tâm văn hóa",
     0.0, "Kính cường lực laminated 15-22mm", "22mm",
     "Không giới hạn (theo kết cấu cáp)", 3000,
     "Cáp inox SUS316 + Cần nhện + Gioăng kín kính", "Silicon kết cấu Dow Corning 983",
     "Kính in kỹ thuật số / Kính frit / Kính Low-E",
     "Mặt kính kéo căng dây inox mảnh, nhìn thuần túy kính không thấy frame, rất nghệ thuật",
     "Thi công cực phức tạp, yêu cầu kỹ sư kết cấu chuyên biệt, giá rất cao",
     "✗", "✗", "✓", "✗", "Đang nghiên cứu", 30, "", ""),
]
